# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161021125907 on 2016-10-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
    ]
