# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161021125907 on 2016-10-23 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
