# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161021125907 on 2016-10-23 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Folder'),
        ),
    ]
