# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161021125907 on 2016-10-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_computer_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='comments',
            field=models.TextField(max_length=300),
        ),
    ]
